spring:
  application.name: app
  liquibase:
    enabled: true
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
  r2dbc:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
logging:
  level:
    org.springframework.data.r2dbc: DEBUG