server.port: 8083

spring:
  application.name: app
  r2dbc:
    url: r2dbc:pool:postgres://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
